Polish help and error messages related to optional dependency on galaxy-lib.
Previously the new options would always be supressed in `cwltool --help`, now they will show up only if galaxy-lib is available.

I've also unified and improved the wording around the exceptions that get raised when these options are used but galaxy-lib is unavailable.

```
cwltool --beta-conda-dependencies tests/seqtk_seq.cwl tests/seqtk_seq_job.json                                    master ✭ ✱ ◼
/Users/john/workspace/cwltool/.venv/bin/cwltool 1.0.20170708080313
Resolved 'tests/seqtk_seq.cwl' to 'file:///Users/john/workspace/cwltool/tests/seqtk_seq.cwl'
[job seqtk_seq.cwl] /private/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpr1IeGr$ seqtk \
    seq \
    -a \
    /private/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmp9MWLCz/stg52d703ba-c684-46f0-ade9-2ae574004bea/2.fastq > /private/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpr1IeGr/out
Exception while running job
Traceback (most recent call last):
  File "build/bdist.macosx-10.12-x86_64/egg/cwltool/job.py", line 197, in _execute
    job_script_contents = builder.build_job_script(commands)
  File "build/bdist.macosx-10.12-x86_64/egg/cwltool/builder.py", line 59, in build_job_script
    return build_job_script_method(self, commands)
  File "build/bdist.macosx-10.12-x86_64/egg/cwltool/software_requirements.py", line 64, in build_job_script
    ensure_galaxy_lib_available()
  File "build/bdist.macosx-10.12-x86_64/egg/cwltool/software_requirements.py", line 121, in ensure_galaxy_lib_available
    raise Exception("Optional Python library galaxy-lib not available, it is required for this configuration.")
Exception: Optional Python library galaxy-lib not available, it is required for this configuration.
[job seqtk_seq.cwl] completed permanentFail
{}
Final process status is permanentFail
```